name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of AbletonMCP would this affect?
      options:
        - Remote Script (new Ableton command)
        - MCP Server
        - REST API Server
        - Max for Live Device
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: What would you like?
      description: Describe the feature or improvement you'd like to see
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use case
      description: How would you use this feature in your workflow?
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Have you tried any workarounds?
    validations:
      required: false
